export const romanianLocations = {
  Alba: ["Alba Iulia", "Aiud", "Blaj", "Cugir", "Sebes", "Teius", "Zlatna"],
  Arad: ["Arad", "Chisineu-Cris", "Ineu", "Lipova", "Nadlac", "Pancota"],
  Arges: ["Pitesti", "Campulung", "Curtea de Arges", "Mioveni", "Stefanesti", "Topoloveni"],
  Bacau: ["Bacau", "Moinesti", "Onesti", "Buhusi", "Comanesti", "Targu Ocna"],
  Bihor: ["Oradea", "Beius", "Marghita", "Salonta", "Sacueni", "Valea lui Mihai"],
  "Bistrita-Nasaud": ["Bistrita", "Beclean", "Nasaud", "Sangeorz-Bai"],
  Botosani: ["Botosani", "Dorohoi", "Darabani", "Saveni"],
  Brasov: ["Brasov", "Codlea", "Fagaras", "Rasnov", "Sacele", "Zarnesti"],
  Braila: ["Braila", "Faurei", "Ianca", "Insuratei"],
  Bucuresti: ["Bucuresti", "Sector 1", "Sector 2", "Sector 3", "Sector 4", "Sector 5", "Sector 6"],
  Buzau: ["Buzau", "Nehoiu", "Patarlagele", "Ramnicu Sarat"],
  "Caras-Severin": ["Resita", "Caransebes", "Bocsa", "Moldova Noua", "Oravita", "Otelu Rosu"],
  Calarasi: ["Calarasi", "Budesti", "Fundulea", "Lehliu Gara", "Oltenita"],
  Cluj: ["Cluj-Napoca", "Campia Turzii", "Dej", "Gherla", "Huedin", "Turda"],
  Constanta: ["Constanta", "Cernavoda", "Eforie", "Mangalia", "Medgidia", "Navodari", "Ovidiu"],
  Covasna: ["Sfantu Gheorghe", "Baraolt", "Covasna", "Intorsura Buzaului", "Targu Secuiesc"],
  Dambovita: ["Targoviste", "Fieni", "Gaesti", "Moreni", "Pucioasa", "Titu"],
  Dolj: ["Craiova", "Bailesti", "Calafat", "Dabuleni", "Filiasi", "Segarcea"],
  Galati: ["Galati", "Beresti", "Targu Bujor", "Tecuci"],
  Giurgiu: ["Giurgiu", "Bolintin-Vale", "Mihailesti"],
  Gorj: ["Targu Jiu", "Bumbesti-Jiu", "Motru", "Novaci", "Rovinari", "Targu Carbunesti"],
  Harghita: ["Miercurea Ciuc", "Baile Tusnad", "Gheorgheni", "Odorheiu Secuiesc", "Toplita"],
  Hunedoara: ["Deva", "Brad", "Hateg", "Hunedoara", "Lupeni", "Orastie", "Petrosani"],
  Ialomita: ["Slobozia", "Amara", "Fetesti", "Tandarei", "Urziceni"],
  Iasi: ["Iasi", "Harlau", "Pascani", "Podu Iloaiei", "Targu Frumos"],
  Ilfov: ["Chitila", "Buftea", "Bragadiru", "Magurele", "Otopeni", "Pantelimon", "Popesti-Leordeni", "Voluntari"],
  Maramures: ["Baia Mare", "Baia Sprie", "Borsa", "Sighetu Marmatiei", "Targu Lapus", "Viseu de Sus"],
  Mehedinti: ["Drobeta-Turnu Severin", "Baia de Arama", "Orsova", "Strehaia", "Vanju Mare"],
  Mures: ["Targu Mures", "Ludus", "Reghin", "Sighisoara", "Sovata", "Tarnaveni"],
  Neamt: ["Piatra Neamt", "Bicaz", "Roman", "Roznov", "Targu Neamt"],
  Olt: ["Slatina", "Bals", "Caracal", "Corabia", "Draganesti-Olt", "Scornicesti"],
  Prahova: ["Ploiesti", "Azuga", "Baicoi", "Busteni", "Campina", "Mizil", "Sinaia"],
  Salaj: ["Zalau", "Cehu Silvaniei", "Jibou", "Simleu Silvaniei"],
  "Satu Mare": ["Satu Mare", "Ardud", "Carei", "Livada", "Negresti-Oas", "Tasnad"],
  Sibiu: ["Sibiu", "Agnita", "Avrig", "Cisnadie", "Medias", "Saliste"],
  Suceava: ["Suceava", "Campulung Moldovenesc", "Falticeni", "Gura Humorului", "Radauti", "Vatra Dornei"],
  Teleorman: ["Alexandria", "Rosiori de Vede", "Turnu Magurele", "Videle", "Zimnicea"],
  Timis: ["Timisoara", "Buzias", "Deta", "Faget", "Giroc", "Lugoj", "Sannicolau Mare"],
  Tulcea: ["Tulcea", "Babadag", "Isaccea", "Macin", "Sulina"],
  Vaslui: ["Vaslui", "Barlad", "Husi", "Murgeni", "Negresti"],
  Valcea: ["Ramnicu Valcea", "Babeni", "Baile Govora", "Baile Olanesti", "Calimanesti", "Dragasani"],
  Vrancea: ["Focsani", "Adjud", "Marasesti", "Odobesti", "Panciu"]
};

export const countyOptions = Object.keys(romanianLocations);
